version: '3.8'
services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=library_manager
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: