version: '3.8'
services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=mikhailpankin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=library_manager
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: