version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=library_manager
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database:/var/lib/postgresql/data
  server:
    build: .
    ports:
      - "5757:5757"
    restart: always
    depends_on:
      - db
volumes:
  database: